name: adventofcode
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  async: ^2.10.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
